
spring.application.name=student-preparation-tracker

# ================= DATABASE =================

# spring.datasource.url=jdbc:postgresql://localhost:5432/student_preparation_tracker
# spring.datasource.username=postgres


spring.datasource.password=${POST_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}


# ================= JPA / HIBERNATE =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= SERVER =================
server.port=8080

# ================= BREVO EMAIL =================
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}

# ================= GEMINI AI =================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash


# =====================================================
# SUPABASE STORAGE
# =====================================================




supabase.url=${SUPABASE_URL}
supabase.bucket=${SUPABASE_BUCKET}
supabase.s3.endpoint=${SUPABASE_S3_ENDPOINT}
supabase.s3.region=${SUPABASE_S3_REGION}
supabase.s3.access-key=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.secret-key=${SUPABASE_S3_SECRET_KEY}