package com.pravallika.student_preparation_tracker.entity;

import jakarta.persistence.*;

@Entity
@Table(
    name = "push_subscriptions",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_push_subscription_endpoint",
            columnNames = "endpoint"
        )
    }
)
public class PushSubscription {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // User who owns this browser subscription
    @Column(nullable = false)
    private String userEmail;

    // Browser push endpoint
    @Column(nullable = false, length = 2000)
    private String endpoint;

    // Public encryption key generated by the browser
    @Column(nullable = false, length = 1000)
    private String p256dh;

    // Authentication secret generated by the browser
    @Column(nullable = false, length = 1000)
    private String auth;

    public PushSubscription() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getEndpoint() {
        return endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getP256dh() {
        return p256dh;
    }

    public void setP256dh(String p256dh) {
        this.p256dh = p256dh;
    }

    public String getAuth() {
        return auth;
    }

    public void setAuth(String auth) {
        this.auth = auth;
    }
}